-- Dizzy Toad Woodworks — seed the current 22 pieces.
-- Run AFTER schema.sql, in the Supabase SQL Editor. Safe to re-run.

insert into public.pieces (id,name,category,species,dimensions,price,status,photos,description,care,sort) values
(1,'Live-Edge Burl Bowl with Turquoise Inlay','bowl','Maple Burl','13" × 5"',225,'available','["photos/burl-turquoise.jpg"]'::jsonb,'The showpiece of the bench. Turned from a wild burl with the natural bark edge left intact, and the bark voids filled with a band of turquoise inlay that catches the light. There is exactly one of these — there can only ever be one.','Decorative or light dry use. Dust with a soft cloth; keep out of direct sun. A little paste wax keeps the figure and inlay glowing.',0),
(2,'Black Walnut Live-Edge Bowl','bowl','Black Walnut','12" × 4"',150,'available','["photos/walnut-liveedge-1.jpg","photos/walnut-liveedge-2.jpg","photos/walnut-liveedge-3.jpg","photos/walnut-liveedge-stamp.jpg"]'::jsonb,'Deep, dark walnut with the natural live edge and bark inclusions left wild around the rim, and dramatic grain swirling in the bottom. Signed on the base with the Dizzy Toad stamp. A true statement piece.','Hand wash and dry immediately. Re-oil with food-safe mineral oil when the wood looks dry. Never the dishwasher.',1),
(3,'Walnut Bowl with Turquoise Vein','bowl','Black Walnut','9" × 3"',140,'available','["photos/walnut-turquoise.jpg"]'::jsonb,'A smooth walnut bowl with a natural crack reclaimed as a feature — filled with a vein of turquoise inlay that runs across the wall like a little river. Dark wood, bright stone, no two ever the same.','Decorative or light dry use. Wipe clean and dry; keep out of standing water. A touch of oil now and then keeps the walnut rich.',2),
(4,'Spalted Maple Bowl','bowl','Spalted Maple','11" × 4"',120,'available','["photos/spalted-bowl-1.jpg","photos/spalted-bowl-2.jpg","photos/spalted-bowl-3.jpg"]'::jsonb,'Black spalting lines wander through pale maple like ink — nature drew every one. Wide and welcoming, equally at home holding fruit or sitting empty as a centerpiece. No two alike.','Hand wash with warm water and mild soap, dry right away. Feed with food-safe mineral oil every few weeks.',3),
(5,'Nested Spalted Bowl Set','bowl','Spalted Maple','set of three, to ~13"',165,'available','["photos/nested-set-1.jpg","photos/nested-set-2.jpg"]'::jsonb,'Three spalted maple bowls turned to nest inside one another — a big serving bowl, a middle, and a little one, all cut from the same character-rich board so the figure carries through the set.','Hand wash and dry immediately. Oil regularly with food-safe mineral oil. Store nested with a cloth between to protect the rims.',4),
(6,'Ash Bowl','bowl','Ash','10" × 3.5"',85,'available','["photos/ash-bowl-1.jpg","photos/ash-bowl-2.jpg"]'::jsonb,'Clean, pale ash with bold cathedral grain sweeping around the bowl. Light, bright, and built for everyday — the bowl that ends up holding everything.','Hand wash only, dry immediately. Re-oil with food-safe mineral oil when it looks dry.',5),
(7,'Black Walnut Salad Bowl','bowl','Black Walnut','11" × 4.5"',130,'available','["photos/walnut-salad-1.jpg","photos/walnut-salad-2.jpg"]'::jsonb,'A big, rich walnut salad bowl with a smooth sweep and deep chocolate grain. The centerpiece your table has been waiting for.','Hand wash only, dry immediately. Oil regularly with food-safe mineral oil. Not for the dishwasher or microwave.',6),
(8,'Smooth Black Walnut Bowl','bowl','Black Walnut','8" × 3.5"',90,'sold','["photos/walnut-bowl-1.jpg","photos/walnut-bowl-2.jpg"]'::jsonb,'Clean and classic — no live edge, just flawless dark walnut grain and a smooth sweep to the rim. The everyday bowl you''ll reach for without thinking.','Hand wash only, dry immediately. Oil regularly with food-safe mineral oil.',7),
(9,'Spalted Maple Vase','vase','Spalted Maple','4" × 10"',110,'available','["photos/vase-curvy-1.jpg","photos/vase-curvy-2.jpg","photos/vase-curvy-3.jpg"]'::jsonb,'A graceful curved vase in spalted maple, with figure running top to bottom. Shown here with hydrangeas — beautiful with a few stems or standing on its own.','For decorative use. Wipe with a soft dry cloth; keep out of direct sun. Use a liner or dried stems rather than standing water.',8),
(10,'Tall Spalted Vase','vase','Spalted Maple','4" × 11"',95,'available','["photos/vase-tall-1.jpg","photos/vase-tall-2.jpg"]'::jsonb,'A taller, straighter take with a flared lip and bold spalting streaks. Statuesque on a mantel or an entry table.','For decorative use. Dust with a soft cloth; keep out of direct sun and away from heat.',9),
(11,'Dark Spalted Vase','vase','Spalted Hardwood','4" × 10"',105,'available','["photos/vase-dark.jpg"]'::jsonb,'A darker vessel with dramatic black spalt lines and a live-edge collar at the rim. Brooding and beautiful.','For decorative use. Wipe with a soft dry cloth; keep out of direct sun.',10),
(12,'Cherry Christmas Tree','christmas_tree','Cherry','4" × 9"',38,'available','["photos/tree-cherry.jpg"]'::jsonb,'Hand-turned tabletop tree with tiered, swept boughs and a slender turned finial on top, in warm cherry that only deepens with age. A keepsake that comes back out every December.','Dust with a soft cloth. No water needed. Store cool and dry off-season.',11),
(13,'Walnut Christmas Tree','christmas_tree','Black Walnut','4" × 10"',42,'available','["photos/tree-walnut-1.jpg","photos/tree-walnut-2.jpg"]'::jsonb,'Tiered turned tree in dark walnut, layered rings climbing to a fine finial. Striking against a string of lights.','Dust with a soft cloth. No water needed. Store cool and dry off-season.',12),
(14,'Garden Mushroom — Tall','mushroom','Mixed Hardwood','≈ 7" tall',34,'available','["photos/mushroom-light-1.jpg","photos/mushroom-light-2.jpg","photos/mushroom-light-3.jpg"]'::jsonb,'A long-stemmed toadstool with the natural bark left as a band beneath the cap — a little woodland magic for a flower bed, a planter, or a shelf. No two caps are ever alike.','Wipe with a soft cloth. Happy indoors or for a spell in the garden; bring it in for winter and a coat of wax now and then keeps it good.',13),
(15,'Walnut Garden Mushroom','mushroom','Black Walnut','≈ 7" tall',38,'available','["photos/mushroom-dark-1.jpg","photos/mushroom-dark-2.jpg"]'::jsonb,'Same woodland charm in dark walnut, with a rugged bark band rimming the cap. Rich and moody tucked among the greenery.','Wipe with a soft cloth. Bring it indoors for winter; a little wax keeps the walnut deep and dark.',14),
(16,'Toadstool Cluster','mushroom','Mixed Hardwood','set of small toadstools',28,'available','["photos/mushroom-cluster.jpg"]'::jsonb,'A little family of turned toadstools in different woods and sizes — they look right at home nestled in the garden or grouped on a windowsill. Collect a few.','Wipe with a soft cloth. A little wax keeps the shine; bring them in for the winter.',15),
(17,'Ash Plate','platter','Ash','9" × 1"',45,'available','["photos/ash-plate.jpg"]'::jsonb,'A wide, shallow plate in pale ash with a gentle rim and beautiful ring grain. Lovely under candles, as a catch-all, or holding bread at the table.','Hand wash and dry. Oil occasionally with food-safe mineral oil to keep it bright.',16),
(18,'Lidded Keepsake Box','box','Maple & Walnut','4" × 5"',55,'available','["photos/lidded-box-1.jpg","photos/lidded-box-2.jpg"]'::jsonb,'A turned box with a snug fitted lid and a slender dark finial for a handle. Just right for rings, earrings, or small keepsakes — a little treasure that holds treasures.','Dust with a soft cloth. Keep dry and out of direct sun.',17),
(19,'Wooden Snowman','snowman','Maple','≈ 6" tall',35,'available','["photos/snowman-1.jpg","photos/snowman-2.jpg"]'::jsonb,'A stacked, hand-turned snowman with a burned-in face, buttons, and a top hat. A keepsake that comes back out every winter for a lifetime.','Dust with a soft cloth. No water needed. Store cool and dry off-season.',18),
(20,'Wine Bottle Stopper','bottle_stopper','Cherry','≈ 4" tall',22,'available','["photos/stopper.jpg"]'::jsonb,'Hand-turned hardwood top on a food-safe stainless stopper. Seals any standard wine or oil bottle, and every grain pattern is one of a kind.','Wipe the wood with a dry cloth. Hand wash the stainless base only; keep the wood out of standing water.',19),
(21,'Wooden Scoop','other','Spalted Maple','≈ 6" long',26,'available','["photos/scoop.jpg"]'::jsonb,'A hand-shaped scoop carved from a single piece of spalted maple — perfect for coffee, salts, or flour, and pretty enough to leave out on the counter.','Hand wash and dry right away. Oil with food-safe mineral oil now and then; never soak or dishwash.',20),
(22,'Pepper Mill','peppermill','Spalted Maple','≈ 8" tall',45,'available','["photos/peppermill.jpg"]'::jsonb,'A turned spalted-maple mill with a quality grinding mechanism inside. Grinds pepper or salt, and looks the part on any table.','Wipe with a dry cloth. Keep dry; refill through the top. Do not immerse.',21)
on conflict (id) do update set
  name=excluded.name, category=excluded.category, species=excluded.species,
  dimensions=excluded.dimensions, price=excluded.price, status=excluded.status,
  photos=excluded.photos, description=excluded.description, care=excluded.care, sort=excluded.sort;
